sudo: required
services:
  - docker

before_install:
  - docker build -t denzilm2417/docker-react -f Dockerfile.dev .

script:
  - docker run denzilm2417/docker-react npm run test -- --watchAll=false
